// <auto-generated />
using System;
using MetWorkingMatch.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MetWorkingMatch.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("MetWorkingMatch.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdAmigo")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("dataConexao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("MetWorkingMatch.Domain.Entities.PedidoMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataAceite")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdUserAprovador")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUserSolicitante")
                        .HasColumnType("char(36)");

                    b.Property<int?>("idStatusSolicitacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idStatusSolicitacaoId");

                    b.ToTable("PedidosMatch");
                });

            modelBuilder.Entity("MetWorkingMatch.Domain.Entities.StatusPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricaoStatus")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("StatusPedido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            descricaoStatus = "Pendente"
                        },
                        new
                        {
                            Id = 2,
                            descricaoStatus = "Aceito"
                        },
                        new
                        {
                            Id = 3,
                            descricaoStatus = "Recusado"
                        });
                });

            modelBuilder.Entity("MetWorkingMatch.Domain.Entities.PedidoMatch", b =>
                {
                    b.HasOne("MetWorkingMatch.Domain.Entities.StatusPedido", "idStatusSolicitacao")
                        .WithMany()
                        .HasForeignKey("idStatusSolicitacaoId");

                    b.Navigation("idStatusSolicitacao");
                });
#pragma warning restore 612, 618
        }
    }
}
